"""<create tables>

Revision ID: f23533ce6f35
Revises: 
Create Date: 2023-06-29 15:31:39.630073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23533ce6f35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('dep_date', sa.Date(), nullable=True),
    sa.Column('arr_airport', sa.String(), nullable=True),
    sa.Column('dep_airport', sa.String(), nullable=True),
    sa.Column('seat_class', sa.String(), nullable=True),
    sa.Column('airline', sa.String(), nullable=True),
    sa.Column('ground_service', sa.String(), nullable=True),
    sa.Column('air_service', sa.String(), nullable=True),
    sa.Column('comfort', sa.String(), nullable=True),
    sa.Column('food', sa.String(), nullable=True),
    sa.Column('ife', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('further_comments', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('users')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###
